language: node_js

node_js:
  - "5"

services:
  - mongodb

# C++11 Node Module Support
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# Istanbul Code Coverage for Coveralls.io
after_script: >
  NODE_ENV=test ./node_modules/.bin/istanbul cover
  ./node_modules/.bin/_mocha --report lcovonly -- -R spec &&
  cat ./coverage/lcov.info | ./node_modules/.bin/coveralls &&
  rm -rf ./coverage
